import '@/styles/globals.css'

export const metadata = {
  title:'WhiskyCommunity',
  description:'Generated by Jinseok',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <h1 className='mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl'><a href="/">WhiskyCommunity</a></h1>
        <ol>
          <li>
            <a href="/whisky">whisky</a>
          </li>
          <li>
            <a href="/review">review</a>
          </li>
          <li>
            <a href="/mypage">mypage</a>
          </li>
        </ol>
        {children}
      </body>
    </html>
  );
}